language: cpp

dist: xenial

services:
  - docker

matrix:
  include:
    - name: "CentOS 7"
      env: PLATFORM=el7 CTEST_CMD="scl enable devtoolset-7 rh-python36 -- ctest3"
    - name: "Fedora 28"
      env: PLATFORM=f28 CTEST_CMD="cmake/bin/ctest"
    - name: "Unbuntu 18.04"
      env: PLATFORM=bionic CTEST_CMD="cmake/bin/ctest"
    - name: "Unbuntu 18.10"
      env: PLATFORM=cosmic CTEST_CMD="ctest"

before_install:
  - docker build -t hevx.$PLATFORM -f test/Dockerfile.$PLATFORM .

script:
  - docker run hevx.$PLATFORM $CTEST_CMD -V -S CTestScript.cmake
