language: cpp

dist: xenial

services:
  - docker

env:
  global:
    - CTEST_SCRIPT_URI=https://raw.githubusercontent.com/usnistgov/hevx/master/test/CTestScript.cmake

matrix:
  include:
    - name: "CentOS 7 (GCC 7.3.1)"
      env: PLATFORM=el7 CTEST_CMD="scl enable devtoolset-7 rh-python36 -- ctest3 -VV"
    - name: "Fedora 28 (GCC 8.2.1)"
      env: PLATFORM=f28 CTEST_CMD="ctest -VV"
    - name: "Fedora 29 (GCC 8.2.1)"
      env: PLATFORM=f29 CTEST_CMD="ctest -VV"
    - name: "Unbuntu 16.04 (GCC 7.4.0)"
      env: PLATFORM=bionic CTEST_CMD="cmake/bin/ctest -VV"
    - name: "Unbuntu 18.04 (GCC 7.3.0)"
      env: PLATFORM=bionic CTEST_CMD="cmake/bin/ctest -VV"
    - name: "Unbuntu 18.10 (GCC 8.2.0)"
      env: PLATFORM=cosmic CTEST_CMD="ctest -VV"

before_install:
  - docker build -t hevx.$PLATFORM -f test/Dockerfile.$PLATFORM .

script:
  - docker run hevx.$PLATFORM /bin/sh -c "curl -O $CTEST_SCRIPT_URI; $CTEST_CMD -V -S CTestScript.cmake"
