language: cpp
dist: trusty
sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - python3-pip
    - g++-7
    - libx11-dev
    - libxrandr-dev

install:
- PROJ_DIR=`pwd`
- DEPS_DIR="${HOME}/deps"
- mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
- CMAKE_URL="https://cmake.org/files/v3.11/cmake-3.11.4-Linux-x86_64.tar.gz"
- mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
- export PATH=${DEPS_DIR}/cmake/bin:${PATH}
- cmake --version
- VULKAN_URL="https://sdk.lunarg.com/sdk/download/1.1.82.1/linux/vulkansdk-linux-x86_64-1.1.82.1.tar.gz"
- mkdir vulkan && travis_retry wget --no-check-certificate -quiet -O - ${VULKAN_URL} | tar --strip-comonents=1 -xz -C vulkan
- export PATH=${DEPS_DIR}/vulkan/x86_64/bin:${PATH}
- glslangValidator --version
- pip3 install --user wheezy.template
- cd ${PROJ_DIR}

script:
- CXX=g++-7 CC=gcc-7 VULKAN_SDK_DIR=${DEPS_DIR}/vulkan/x86_64 cmake .
- cmake --build .

