language: generic
dist: trusty
sudo: false

matrix:
  include:
  - env: COMPILER_NAME=gcc CXX=g++-7 CC=gcc-7
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - python3-pip
        - g++-7
        - libx11-dev
        - libxrandr-dev
  - env: COMPILER_NAME=clang CXX=clang++-6.0 CC=clang-6.0
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-7
        - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-7 main'
          key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
        packages:
        - python3-pip
        - g++-7
        - clang-7
        - libc++1-7
        - libc++abi1-7
        - libc++-7-dev
        - libc++abi-7-dev
        - libx11-dev
        - libxrandr-dev

install:
- CMAKE_URL="https://cmake.org/files/v3.11/cmake-3.11.4-Linux-x86_64.tar.gz"
- mkdir ${HOME}/cmake && travis_retry wget --no-check-certificate --quiet -O - "${CMAKE_URL}" | tar --strip-components=1 -xz -C ${HOME}/cmake
- VULKAN_URL="https://sdk.lunarg.com/sdk/download/1.1.82.1/linux/vulkansdk-linux-x86_64-1.1.82.1.tar.gz?u="
- mkdir ${HOME}/vulkan && travis_retry wget --no-check-certificate --quiet -O - "${VULKAN_URL}" | tar --strip-components=1 -xz -C ${HOME}/vulkan
- pip3 install --user wheezy.template

env:
  global:
  - PATH=${HOME}/cmake/bin:${HOME}/vulkan/x86_64/bin:${PATH}
  - VULKAN_SDK=${HOME}/vulkan/x86_64

script:
- cmake -DPYTHON_EXECUTABLE=/opt/pyenv/shims/python3 -DBUILD_DOCS=OFF .
- cmake --build .
