language: cpp

dist: xenial

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - python3
            - python3-pip
            - python3-setuptools
            - g++-7
            - libx11-dev
            - libx11-xcb-dev
            - libxrandr-dev
            - libxcb1-dev
            - libxcb-icccm4-dev

env:
  - CMAKE_CONFIG="-DBUILD_DOCS=OFF -DBUILD_DEPENDENCY_TESTING=OFF" CC=gcc-7 CXX=g++-7

install:
  - pip3 install --user wheezy.template

script:
  - cmake ${CMAKE_CONFIG} -DCMAKE_BUILD_TYPE=Release -H. -Bb && cmake --build b -- -j
