language: cpp
script: cmake
dist: trusty
sudo: false
python:
  - "3.6"
before_install:
  - sudo apt-get install -y python
install:
  - pip3 install --user wheezy.template
compiler:
  - gcc
  - clang
addons:
  apt:
    update: true
