language: cpp

dist: xenial

python:
  - "3.7"

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libx11-dev
            - libx11-xcb-dev
            - libxrandr-dev
            - libxcb1-dev
            - libxcb-icccm4-dev

env:
  - CC=gcc-7
  - CXX=g++-7
  - CMAKE_CONFIG="-DBUILD_DOCS=OFF -DBUILD_DEPENDENCY_TESTING=OFF"

install:
  - pip3 install --user wheezy.template

script:
  - cmake ${CMAKE_CONFIG} -H. -Bb
  - cmake --build b
