language: cpp
dist: trusty
sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - python3-pip
    - g++-7

install:
- pip3 install --user wheezy.template

script:
- CXX=/usr/bin/g++-7 CC=/usr/bin/gcc-7 cmake .
- cmake --build .

